### ISSUE TITLE
SCP-079 Rework

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#10]
https://www.civilgamers.com/community/threads/scp-079-buff-and-a-misc-change.3831/#post-25238

**Comment by CoolfraeCN** [comment]
1. Make is to the person playing SCP-079 can change the monitor of the SCP to the face that is present on the SCP in lore or the X (would be good RP for tests) If this is too hard to implement make it so there is an X when he is not breached and a face when he is, this wouldn't change anything in gameplay because when you enter his CC you can check the containment thing to see if he is breached or not)

2. Make it so he can toggle teslas (trigger the shock on command)

3. Make it so the "wire" doesnt show when he is hacking something,

**Comment by Kw1ll** [comment]
Closed to reduce backlog - 079 is currently in a stable place in the meta, no need to add further features.
