### ISSUE TITLE
Remove /g (Group Chat)

### ISSUE THREAD

**Issue by Nilskatten** [civilnetworks/SCP_Public_Development#185]
Often used to metagame or move information between users without any third party know.

**Comment by Kw1ll** [comment]
Delete it from D-class, leave elsewhere

**Comment by K2Cr** [comment]
Issue complete, however could not leave elsewhere for now due to an incompatibility with VJobEditor, if you want the group chats for specific sets of people please make another issue with the jobs you want to share a group chat, i.e. for MTF E-11 all the jobs in MTF E-11, ideally in the TEAM_E11_WHATEVER_ROLE format.

**Comment by K2Cr** [comment]
Disregard previous, non D-Class or potential minge job categories now all share their group chats.
